name: youtube_mp3_downloader
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  path_provider: ^2.0.5
  permission_handler: ^10.4.1
  youtube_explode_dart: ^1.12.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
